branches:
  only:
  - master
language: node_js
node_js: stable
install:
  - npm install gulp-cli -g
  - npm install
before_script:
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/mimoduo/mimogear.git"
  - git config --global user.email "mimoduo@gmail.com"
  - git config --global user.name "Travis-CI"
script:
  - gulp ghPages --base --min --production
after_success:
  - surge --project ./dist --domain mimogear.surge.sh
